### ISSUE TITLE
Very bad clover

### ISSUE THREAD

**Issue by dominikzorgie** [sbwml/EFI-os10.15.x_b360m_pro4#1]
yes ur EFI is working, but it's very dirty and include many kexts and patch which no needed to AsRock B360M Pro4 MOBO.

**Comment by sbwml** [comment]
This is not the basic EFI of b360 pro4. The kexts and patch it contains are all needed by my own computer. It is just a backup.

**Comment by dominikzorgie** [comment]
y no need to disable laptop  touchpad, and cardreader because u doesnt' have laptop. U just pull many useless kexts and patch into clover.

**Comment by L4Liyooooo** [comment]
老哥有qq吗 可以加你请教几个问题吗？

**Comment by sbwml** [comment]
> 老哥有qq吗 可以加你请教几个问题吗？

admin@cooluc.com
